apiVersion: v1
kind: Service
metadata:
  name: archive-client
  namespace: utm-archive
  labels:
    app.kubernetes.io/name: archive-client
    app.kubernetes.io/part-of: utm-archive
  annotations:
    cloud.google.com/backend-config: '{"default":"archive-client-backendconfig"}'
spec:
  selector:
    app.kubernetes.io/name: archive-client
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: archive-client-backendconfig
  namespace: utm-archive
  labels:
    app.kubernetes.io/name: archive-client
    app.kubernetes.io/part-of: utm-archive
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archive-client
  namespace: utm-archive
  labels:
    app.kubernetes.io/name: archive-client
    app.kubernetes.io/part-of: utm-archive
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: archive-client
  template:
    metadata:
      labels:
        app.kubernetes.io/name: archive-client
        app.kubernetes.io/part-of: utm-archive
    spec:
      containers:
        - name: archive-client
          image: __ARCHIVE_CLIENT_IMAGE__
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 6
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
